## Numpy

In [1]:
import numpy as np

In [5]:
# Arange
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# linspace
# Return evenly spaced numbers over a specified interval.

In [6]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [7]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [8]:
# rand
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [10]:
np.random.rand(2)

array([0.46840552, 0.40151467])

In [11]:
np.random.rand(5,5)

array([[0.02165108, 0.26042548, 0.32908412, 0.64650093, 0.5746883 ],
       [0.0617865 , 0.41649265, 0.81351617, 0.84381194, 0.13039924],
       [0.55428978, 0.34155862, 0.04446489, 0.29275588, 0.86470114],
       [0.49759331, 0.1612978 , 0.78119962, 0.20364412, 0.80208924],
       [0.61826661, 0.79317158, 0.62874222, 0.05143294, 0.85242366]])

In [12]:
#randn
#Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [13]:
np.random.randn(2)

array([0.37514483, 0.50432803])

In [14]:
np.random.randn(5,5)

array([[ 0.93868326,  0.99462201, -0.5149505 , -0.87755667, -0.85106168],
       [-0.11347623,  1.28297581, -0.94963147, -0.07847318, -1.48677222],
       [-0.04878493,  0.81978517,  0.35191084,  1.82853994, -2.02704089],
       [-0.50729594, -2.24180507,  1.06292112, -0.31732995,  1.36839728],
       [-0.39673607, -0.99449463, -0.95228701, -0.45446104,  0.54214906]])

In [ ]:
# randint
# Return random integers from low (inclusive) to high (exclusive).

In [15]:
np.random.randint(1,100)

87

In [16]:
np.random.randint(1,100,10)

array([44, 24, 31, 12, 98, 86, 40, 13, 74, 47])

In [19]:
# Reshape
# Returns an array containing the same data with a new shape.

In [17]:
arr = np.arange(25)

In [18]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [20]:
#Get a value at an index
arr[8]

np.int64(8)

In [21]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [22]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [23]:
arr[:5]

array([0, 1, 2, 3, 4])

In [24]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

# Series
#### pandas.Series(data=None, index=None, dtype=None, name=None, copy=None)

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [11]:
d

{'a': 10, 'b': 20, 'c': 30}

In [13]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [25]:
ser1 = pd.Series([1,2,3,4],index=["USA","Germany","USSR","Japan"])

In [27]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [28]:
ser2 = pd.Series([1,2,3,4],index=["USA","Germany","Italy","Japan"])

In [30]:
ser2

USA        1
Germany    2
Italy      3
Japan      4
dtype: int64

In [31]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

# DataFrames
#### pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)

In [51]:
from numpy.random import randn

In [52]:
np.random.randn(5,4)

array([[-0.35343385, -0.77958781,  0.09164352,  3.51283058],
       [-0.55387556,  2.33048709, -0.61205523, -0.06567775],
       [-1.60244941, -0.52379469, -1.41318345, -0.12658092],
       [ 0.31811943, -2.05140517, -0.38737922,  0.18342554],
       [ 0.9567374 , -1.2038852 , -0.57499172,  0.86214355]])

In [53]:
randn(5,4)

array([[ 2.01640311, -0.26678857,  0.1091844 , -1.00086002],
       [ 0.04676305,  0.06499302,  0.81330535,  0.66429038],
       [-0.38718343, -0.47648836, -0.10337966, -0.98318083],
       [-0.01614879,  0.1430641 , -0.17874589,  0.6922759 ],
       [-1.23486149,  1.58506743,  0.35395783, -0.73835787]])

In [95]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [96]:
df

          W         X         Y         Z
A  3.130641  0.166484 -0.046499 -0.636420
B  0.083138  0.022655  0.827579 -0.181257
C -0.042797 -0.658283 -1.712093 -0.374537
D -0.482095  0.182605 -0.614436  0.240677
E  0.894939  0.013462 -0.516986 -0.763386

In [130]:
df[['W','Y']]

          W         Y
A  3.130641 -0.046499
B  0.083138  0.827579
C -0.042797 -1.712093
D -0.482095 -0.614436
E  0.894939 -0.516986

In [98]:
df['new'] = df['W'] + df['X']

In [99]:
df

          W         X         Y         Z       new
A  3.130641  0.166484 -0.046499 -0.636420  3.297124
B  0.083138  0.022655  0.827579 -0.181257  0.105793
C -0.042797 -0.658283 -1.712093 -0.374537 -0.701080
D -0.482095  0.182605 -0.614436  0.240677 -0.299490
E  0.894939  0.013462 -0.516986 -0.763386  0.908401

In [100]:
df.drop('new',axis=1)

          W         X         Y         Z
A  3.130641  0.166484 -0.046499 -0.636420
B  0.083138  0.022655  0.827579 -0.181257
C -0.042797 -0.658283 -1.712093 -0.374537
D -0.482095  0.182605 -0.614436  0.240677
E  0.894939  0.013462 -0.516986 -0.763386

In [101]:
df

          W         X         Y         Z       new
A  3.130641  0.166484 -0.046499 -0.636420  3.297124
B  0.083138  0.022655  0.827579 -0.181257  0.105793
C -0.042797 -0.658283 -1.712093 -0.374537 -0.701080
D -0.482095  0.182605 -0.614436  0.240677 -0.299490
E  0.894939  0.013462 -0.516986 -0.763386  0.908401

In [102]:
df.drop('new',axis=1,inplace=True)

In [103]:
df

          W         X         Y         Z
A  3.130641  0.166484 -0.046499 -0.636420
B  0.083138  0.022655  0.827579 -0.181257
C -0.042797 -0.658283 -1.712093 -0.374537
D -0.482095  0.182605 -0.614436  0.240677
E  0.894939  0.013462 -0.516986 -0.763386

In [104]:
df.drop('E',axis=0)

          W         X         Y         Z
A  3.130641  0.166484 -0.046499 -0.636420
B  0.083138  0.022655  0.827579 -0.181257
C -0.042797 -0.658283 -1.712093 -0.374537
D -0.482095  0.182605 -0.614436  0.240677

In [106]:
df

          W         X         Y         Z
A  3.130641  0.166484 -0.046499 -0.636420
B  0.083138  0.022655  0.827579 -0.181257
C -0.042797 -0.658283 -1.712093 -0.374537
D -0.482095  0.182605 -0.614436  0.240677
E  0.894939  0.013462 -0.516986 -0.763386

In [113]:
df.loc['E']

W    0.894939
X    0.013462
Y   -0.516986
Z   -0.763386
Name: E, dtype: float64

In [114]:
df.iloc[4]

W    0.894939
X    0.013462
Y   -0.516986
Z   -0.763386
Name: E, dtype: float64

In [132]:
df.loc['B','Y']

np.float64(0.8275787398370132)

In [133]:
df.loc[['A','B'],['W','Y']]

          W         Y
A  3.130641 -0.046499
B  0.083138  0.827579

In [134]:
df

          W         X         Y         Z
A  3.130641  0.166484 -0.046499 -0.636420
B  0.083138  0.022655  0.827579 -0.181257
C -0.042797 -0.658283 -1.712093 -0.374537
D -0.482095  0.182605 -0.614436  0.240677
E  0.894939  0.013462 -0.516986 -0.763386

In [135]:
df>0

       W      X      Y      Z
A   True   True  False  False
B   True   True   True  False
C  False  False  False  False
D  False   True  False   True
E   True   True  False  False

In [136]:
df[df>0]

          W         X         Y         Z
A  3.130641  0.166484       NaN       NaN
B  0.083138  0.022655  0.827579       NaN
C       NaN       NaN       NaN       NaN
D       NaN  0.182605       NaN  0.240677
E  0.894939  0.013462       NaN       NaN

In [140]:
df[df['W']>0]

          W         X         Y         Z
A  3.130641  0.166484 -0.046499 -0.636420
B  0.083138  0.022655  0.827579 -0.181257
E  0.894939  0.013462 -0.516986 -0.763386

In [149]:
df[df['W']>0][['Y','X']]

          Y         X
A -0.046499  0.166484
B  0.827579  0.022655
E -0.516986  0.013462

In [155]:
df[(df['X']>0) & (df['W']>1)]

          W         X         Y        Z
A  3.130641  0.166484 -0.046499 -0.63642

In [156]:
df

          W         X         Y         Z
A  3.130641  0.166484 -0.046499 -0.636420
B  0.083138  0.022655  0.827579 -0.181257
C -0.042797 -0.658283 -1.712093 -0.374537
D -0.482095  0.182605 -0.614436  0.240677
E  0.894939  0.013462 -0.516986 -0.763386

In [157]:
df.reset_index()

  index         W         X         Y         Z
0     A  3.130641  0.166484 -0.046499 -0.636420
1     B  0.083138  0.022655  0.827579 -0.181257
2     C -0.042797 -0.658283 -1.712093 -0.374537
3     D -0.482095  0.182605 -0.614436  0.240677
4     E  0.894939  0.013462 -0.516986 -0.763386

In [158]:
newind = 'CA NY WY OR CO'.split()

In [162]:
df['States'] = newind

In [163]:
df

          W         X         Y         Z States
A  3.130641  0.166484 -0.046499 -0.636420     CA
B  0.083138  0.022655  0.827579 -0.181257     NY
C -0.042797 -0.658283 -1.712093 -0.374537     WY
D -0.482095  0.182605 -0.614436  0.240677     OR
E  0.894939  0.013462 -0.516986 -0.763386     CO

In [167]:
df.set_index('States',inplace=True)

In [168]:
df

               W         X         Y         Z
States
CA      3.130641  0.166484 -0.046499 -0.636420
NY      0.083138  0.022655  0.827579 -0.181257
WY     -0.042797 -0.658283 -1.712093 -0.374537
OR     -0.482095  0.182605 -0.614436  0.240677
CO      0.894939  0.013462 -0.516986 -0.763386

### Mising Data

In [198]:
# Create a DataFrame 
# columns = a,b,c
#a = 1,2,NaN
#b = 5,NaN,NaN
#c = 1,2,3

data = [
    [1,5,1],
    [2,np.nan,2],
    [np.nan,np.nan,3]
    
]

In [199]:
df = pd.DataFrame(data,columns='A B C'.split())

In [200]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [216]:
# Create the DataFrame
data = {
    'A':[1,2,np.nan],
    'B':[5,np.nan,np.nan],
    'C':[1,2,3]
}

In [217]:
df = pd.DataFrame(data)

In [218]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [219]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [220]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [227]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [228]:
df.fillna("FILL VALUES")

             A            B  C
0          1.0          5.0  1
1          2.0  FILL VALUES  2
2  FILL VALUES  FILL VALUES  3

In [229]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [230]:
df['A'].mean()

np.float64(1.5)

### Group By

In [231]:
import pandas as pd
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [232]:
df = pd.DataFrame(data)

In [233]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [244]:
df.groupby('Company')

In [245]:
by_compy = df.groupby('Company')

In [262]:
mean_std = df.groupby('Company')['Sales']

In [264]:
mean_std.sum()

Company
FB      593
GOOG    320
MSFT    464
Name: Sales, dtype: int64

In [263]:
mean_std.std()

Company
FB       75.660426
GOOG     56.568542
MSFT    152.735065
Name: Sales, dtype: float64

In [261]:
mean_std.mean()

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

In [248]:
by_compy.min()

          Person  Sales
Company
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [249]:
by_compy.max()

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [250]:
by_compy.count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [251]:
by_compy.describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [252]:
by_compy.describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [257]:
by_compy.describe().transpose()['GOOG']

Sales  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: GOOG, dtype: float64

# Operations

There are lots of operations with pandas that will be really useful to you, but don't fall into any distinct category. Let's show them here in this lecture:

In [37]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [38]:
df['col2'].unique()

array([444, 555, 666])

In [39]:
df['col2'].nunique()

3

In [40]:
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [41]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [42]:
df['col1'].sum()

np.int64(10)

In [43]:
del df['col1']

In [44]:
df

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [52]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [53]:
df.index

RangeIndex(start=0, stop=4, step=1)